/**语言包  cn: 中文包；en：英文包；ja：日文包*/
var cn = {
    //index.html
    navigation_item1: '简介',
    navigation_item2: '背景及问题',
    navigation_item3: '解决方案',
    navigation_item4: '竞争优势',
    navigation_item5: '团队介绍',
    navigation_item6: '社区生态',
    navigation_item7: '博客',
    navigation_item8: '悬赏任务',
    registration_item: '加入白名单',

    sequence_item1: '基于区块链的全球去中心化游戏内容公共社区',
    sequence_item2: '白皮书',
    sequence_item2_first: '白皮书',
    sequence_item2_second: 'ENGLISH',
    sequence_item2_third: '日語',
    sequence_item2_fourth: '加入聊天群',

    //#industry_status
    industry_status_feature: '特点',
    industry_status_item1: '由玩家自治及<span>智能合约</span>执行的游戏和评论内容排行榜与推荐策略，真正做到透明公正，杜绝资本和权势染指。',
    industry_status_item2: '抓<span>原创源头</span>。全球首个能自行开发区块链游戏引擎专业软件的硬核技术团队；BCreator.io支持开发者梦想起航；巨量开发者的聚集地。',
    industry_status_item3: '5G时代重度大型游戏免下载安装<span>即点即玩</span>的新形态入口。<span>移动互联网宽带</span>时代的“HQ HTML5”，无限流量、5G时代重大利好接踵而来，必将成为业界新标准。',
    industry_status_item4: '信誉<span>大数据宝库</span>。开发者、评论者的历史行为均被智能合约<span>烙印</span>在区块链中，可追溯不可篡改，形成各类决策所关键依托的大数据。',

    industry_status_feature1: '虚拟分布式的结构',
    industry_status_feature2: '高效率低成本的运作模式',
    industry_status_feature3: '去中心化的结构',
    industry_status_feature4: '多节点共识机制',
    industry_status_feature5: '分布式记账',

    //#service
    service_title1: '行业',
    service_title2: '背景及问题',
    service_title_item1: '抢占战略高地的窗口期',
    service_text_item1: '中文游戏早不再是增量市场，而是存量时代，品质和可玩性才是关键，游戏正在<span>回归初心</span>，中文玩家<span>正版付费</span>意识全面<span>振兴</span>，中文游戏文艺复兴黄金时代的朝阳正在冉冉升起。当下能以低成本来吸引开发者及其粉丝，是抢夺战略高地的历史难遇的<span>窗口时期</span>。',
    service_title_item2: '游戏众筹模式成熟',
    service_text_item2: '截至2017年9月，全球发起的游戏众筹项目数4万余个，共募集资金9亿美元，参投用户量1500万。反观中文游戏行业却“<span>势能矛盾</span>”突出：一方面愿为优秀游戏作品<span>付费的用户</span>群体已非常庞大，可另一方面有潜力的团队却极<span>难融资</span>，这种势能矛盾急需被一种模式击破“<span>泄洪</span>”。',
    service_title_item3: '区块链+游戏崭露头角',
    service_text_item3: '区块链领域一直缺少能实际落地项目，<span>假大空</span>横行。优秀新技术又一次从游戏领域率先落地实用，更多玩家关注区块链，而币圈投资人更接受游戏类项目。全球通过区块链数字货币方式的融资额已是<span>传统VC的两倍</span>，更是我们众筹模式的<span>N<sub>2</sub>O暴强加速剂</span>。',
    
    //#portfolio
    portfolio_title1: '解决方案',
    portfolio_title2: '与实现',
    portfolio_title_item1: '整体方案',
    portfolio_title_item2: '制作游戏',
    portfolio_title_item3: '玩游戏',
    portfolio_title_item4: '交流游戏',
    portfolio_title_item5: '区块链应用',

    Grid_title_item1: '游戏众筹社区',
    Grid_text_item1: '通过众筹对优秀创意项目进行投资，获得作品及相关资产的预购权乃至升值等回报，项目众筹达到或超过目标额度才算成功，否则全额退还给各资助者。',
    Grid_title_item2: '量身打造的创作利器',
    Grid_text_item2: '提供<span>华语</span>唯一<span>国际</span>水平高品质<span>游戏引擎</span>制作工具BCreator.io（也将发布英文版和日文版），内含图形NLP化<span>免编程</span>制作交互逻辑的模块Director极大降低了技术门槛，以便开发者选用创作游戏。',
    Grid_title_item3: '高品质游戏分发平台',
    Grid_text_item3: '社区吸纳优秀作品和开发者，聚集人气，并通过活动、直播、广告等方式吸引玩家。聚集大量玩家后，又能进一步吸引更多作品和优秀开发者入驻，形成<span>良性循环</span>。',
    Grid_title_item4: '即点即玩HTML5 2.0',
    Grid_text_item4: '实现了大型高品质<span>重度原生</span>游戏的“<span>免下载免安装即点即玩</span>”HTML5化。迎接无限流量、千兆4G、5G<span>移动宽带</span>互联网新时代，建立划时代的新形态的游戏入口模式。',
    Grid_title_item5: '高水准评论',
    Grid_text_item5: '实施<span>竞争</span>和<span>激励</span>机制，以及促进内容筛择评论者群体',
    Grid_title_item6: '直面粉丝意见',
    Grid_text_item6: '玩家与开发者<span>直接交流</span>，打磨作品。',
    Grid_title_item7: 'IM系统',
    Grid_text_item7: 'IM系统，为用户提供<span>即时通讯</span>服务',
    Grid_title_item8: '直播系统',
    Grid_text_item8: '有效提高社区<span>活跃度</span>提高游戏产品<span>收益</span>',
    Grid_title_item9: '互动社区',
    Grid_text_item9: '基于区块链的<span>公正透明</span>的激励机制。玩家、开发者、投资者、评论家、推广者在社区内外互动，互动行为皆由<span>智能合约</span>执行，并<span>烙印</span>至区块链。每一位社区成员都会有主人翁心态来主动推广和建设自己的社区。',
    Grid_title_item10: '区块链存取SDK',
    Grid_text_item10: '基于区块链的SDK，实现去中心化游戏账号及数字财产的<span>确权</span>，以及跨游戏<span>交易贯通</span>。并实现跨游戏的一键登入、平台通证结算手段、以及数字财产确权存取和交易贯通。',
    Grid_title_item11: '良性竞争激励机制',
    Grid_text_item11: '由区块链支撑两大良性竞争激励机制。作品和作品评论UGC的优秀与否，完全由<span>玩家决定</span>，确保社区高品质。区块链保障创始团队在内的任何人和势力均<span>不能控制和篡改</span>这两大竞争激励机制。',
    Grid_title_item12: '信誉数据宝库',
    Grid_text_item12: '通过币天消耗来控制刷信誉行为，每位开发者在社区中的历史成绩和行为、及作品发展的历史轨迹、评论家的评价行为等，都会被智能合约烙印在区块链之中，成为一个<span>可追溯的不可篡改</span>的信誉大数据库。',

    //#competitive
    competitive_title1: '竞争',
    competitive_title2: '优势',
    competitive_title_item1: '签约亿级流水产品',
    competitive_text_item1: '签约<span>亿级</span>月流水头部产品上线平台，社区上线之初即有<span>十数款</span>商业盈利成熟大作。',
    competitive_title_item2: '深厚业内资源',
    competitive_text_item2: '深耕游戏行业核心研发和运营<span>十数年</span>，拥有深厚游戏行业资源、经验和互联网深度人脉。',
    competitive_title_item3: '即点即玩HTML5 2.0',
    competitive_text_item3: '<span>转化现有</span>高品质重度原生游戏为“免下载免安装即点即玩”入口形态。无限流量、千兆4G、5G<span>重大利好</span>接踵而来，<span>移动宽带</span>互联网时代的游戏入口新标准！',
    competitive_title_item4: '国际水平的游戏引擎',
    competitive_text_item4: '国际水平的游戏引擎制作工具Bcreator.io。',
    competitive_title_item5: '成熟直播软件系统',
    competitive_text_item5: '社区内建游戏直播，极大提高社区活跃度和黏着度。',
    competitive_title_item6: '智能合约的图形化免编程编制工具',
    competitive_text_item6: '图形NLP化的<span>免编程</span>智能合约编制工具AISC，摆脱只能由程序员编写智能合约的桎梏，回归传统文字合同编制的便利性。',

    //#price
    price_title1: '产品',
    price_title2: '展示',

    price_item1: '亿元月流水《三国志2017》',
    price_item2: '千万月流水《全民乐舞》',
    price_item3: '无双经典致敬《真三国战纪》',
    price_item4: '现金流游戏《来啊捕鱼》',
    price_item5: '沙特Edu-game《عالم أريب》',
    price_item6: '单月服5万美金《初代吸血鬼》',
    price_item7: '《Beauty and the beast》',
    price_item8: '像素IO游戏《我的坦克》',
    price_item9: 'H5《クリプトアイランド 》',
    price_item10: '《梦幻3D》',
    price_item11: 'H5《直播秀场百人德州》',
    price_item12: '月流水千万《幻想学园》',

    //#team
    team_title: '团队',
    team_title_intro: '介绍',
    team_title1: '主创团队',
    team_title2: '顾问团队',
    team_title3: '合作伙伴',

    team_name_item1: 'Ali Dagli',
    team_text_item1: '加利福利亚伯克利分校金融学博士，数字媒体领域资深投资人和金融战略顾问。在GCA Savvian副总裁，运作了日本社交巨头Gree 2.1亿美金收购Funzio、Saban Brands收购The Playforge等著名案例。自2013年起对区块链金融深入研究和实践。',
    team_name_item2: 'Thomas Lindgren',
    team_text_item2: 'Western University MBA。游戏行业资深人士，曾任瑞典游戏公司Stardoll担任CEO，Fatshark AB 制作人。',
    team_name_item3: 'Oliver Wu',
    team_text_item3: '宾夕法尼亚大学计算机博士，著名经典文字MUD《Three Kindgoms》巫师，《Warhammer: end times》MMO制作人。曾担任新加坡互动媒体中心负责人 ，负责青奥会虚拟现实世界的开发和运营。担任中青宝前海外总裁。',
    team_name_item4: 'Abdullah Konash',
    team_text_item4: '美国哈佛大学音乐艺术理论研究员。沙特阿拉伯游戏设计和开发领域的先驱，在游戏领域有九年的工作经验，并且渴望领导沙特阿拉伯游戏行业的发展。曾任Hako Games，Ranam制作人。',
    
    team_name_item0: '董浩',
    team_text_item0: '上海交通大学软件硕士，完美世界研究中心工程师，VR黄埔军校著称的中视典原CTO，C²engine创始人。15年游戏行业经验，多款盈利商业大作。自2014年即着手研究区块链在游戏行业的应用。',
    
    team_name_item5: '冯涛',
    team_text_item5: '联创永宣董事长。新浪等众多著名商业传奇缔造者，与沈南鹏等入选福布斯中国2017最佳创投人前三甲。区块链领域早期即支持了INB、OK 、 NEO 、 BigONE、Beechat等项目。',
    team_name_item6: 'Frank Liu',
    team_text_item6: '新加坡南洋理工大学博士后研究员，拥有多项专利知识产权，数学功底深厚。对三维图形学、密码学、点对点通讯、区块链共识机制、深度学习有深入研究。',
    team_name_item7: '易理华',
    team_text_item7: '优领资本创始合伙人，INBlockchain（硬币资本）创始合伙人。曾投资量子链、唯链、雷盈、BigONE等30余个区块链项目，涵盖量化基金、区块链母基金、代码审计、交易所等领域。',
    team_name_item8: '谭群钊',
    team_text_item8: '华东理工大学，北京大学EMBA。丰厚资本创始人，盛大联合创始人，曾任盛大游戏董事长兼首席执行官，为盛大游戏、中国游戏产业的发展做出了巨大贡献。',
    team_name_item9: '李翀',
    team_text_item9: '天使投资人，点亮资本发起人，PPTV联合创始人。专注于移动互联网、区块链等领域，涌现出布比区块链、三迪建科、波奇、P2联合办公等一大批优秀项目。',
    team_name_item10: '刘嘉陵（巨蟹）',
    team_text_item10: '国内早期区块链项目布道者和投资者，比特创业营创始成员，比特股和以太坊项目早期参与者，比特股理事会理事、YOYOW团队成员、ATMatrix智能矩阵天使投资人。',
    team_name_item11: '金鹏',
    team_text_item11: '复旦大学哲学博士，师从中共中央政治局常委王沪宁教授。前盛大网络高级副总裁，上海联创管理合伙人，无穹创投创始人，在游戏、娱乐、数字金融及营销领域投资了大量新兴企业。',
    team_name_item12: 'Lee Hills',
    team_text_item12: '电子游戏业务的企业家和资深顾问，擅长新兴行业，专注于区块链和金融科技领域。曾是SolutionsHub Limited创始人，Oliver Charles Sports Management联合创始人。',

    team_name_item13: '毛杰',
    team_text_item13: '原上海钢联副总及董事，从创业到上市一路打拼。上海钢联电子商务股份有限公司（股票代码：300226）是集钢铁资讯、电子商务、网络技术服务为一体的全国性大型综合IT服务企业，提供专业的钢铁资讯交互平台、一站式钢铁电子商务服务。',
    team_name_item14: '辛晓琦',
    team_text_item14: '拥有11年的游戏行业经验，曾经参与过多款大型网络游戏的制作，其中包括《星球大战：旧共和国》。有多年高负荷游戏项目开发的管理经验和运营经验。于2017年加入GAME.FUND，负责社区运营和产品增长等业务。',
    team_work_item3: '创始人 CEO',
    team_work_item0: '联合创始人  CTO',
    team_work_item13: '联合创始人  COO',
    team_work_item6: '系统架构师',
    team_work_item14: '运营总监',

    //#community
    community_title1: '社区',
    community_title2: '生态',
    community_img_title: 'GCC通证分配方案',
    community_title_item1: '社区内容激励  30%',//需要修改
    community_text_item1: '20%的GCC直接投放社区运作',
    community_title_item2: '售卖 40%',
    community_text_item2: '45%的GCC用于社区内容激励，维护社区的高品质良性运作。由智能合约按社区细则客观执行激励。',
    community_title_item3: '顾问  10%',
    community_text_item3: '5%的GCC为早期天使持有，有了他们的支持，社区才有现在的基础，社区运行一年内锁定。',
    community_title_item4: '生态基础激励 10%',
    community_text_item4: '15%的GCC用于激励GameChain生态基础建设者，以及合作伙伴，用以夯实生态体系。',
    community_title_item5: '主创团队 10%',
    community_text_item5: '15%的GCC为主创团队持有，社区运行一年内锁定。',
        
    total_content_item1: 'GCC（GameChain）是本社区通证，拥有GCC是社区成员的标志。GCC总量50亿个，可精确到10<sup>-8</sup>，永不增发。',

    community_video_title: '社区运作',
    video_tag_tip: '您的浏览器不支持video标签',
    community_video_text1: '是不是有点烧脑？没事，您看这一段就能明白',
    community_video_text2: '简单的说，社区各角色价值流转行为都以GCC为流通凭证，币天和币天担保机制鼓励用户持有GCC和避免刷信誉及排名。社区按不同比例收取游戏众筹和游戏发行的分成，此分成收入用作社区建设和维护外，至少50%按GCC持有比例定期分配到对应地址。随着社区的推广扩大，越来多用户加入社区，GCC通证的升值是必然的',

    //#contact
    contact_we: '联系我们',
    contact_broadcast_group: '公告地址：',
    contact_chat_group: '聊天群地址：',
    contact_mail: '邮箱地址：',
    broadcast_group: '广播群',
    chat_group: '聊天群',
}

//-----------------------------------------英文版
var en = {
    //index.html
    navigation_item1: 'Introduction',
    navigation_item2: 'Background',
    navigation_item3: 'Solution',
    navigation_item4: 'Advantage',
    navigation_item5: 'Team',
    navigation_item6: 'Ecology',
    navigation_item7: 'Blog',
    navigation_item8: 'Reward',
    registration_item: 'Join whitelist',

    sequence_item1: 'Blockchain-based global decentralized game content public community.',
    sequence_item2: 'White Papers',
    sequence_item2_first: 'White Papers',
    sequence_item2_second: '中文',
    sequence_item2_third: '日語',
    sequence_item2_fourth: 'JOIN OUR TELEGRAM',

    //#industry_status
    industry_status_feature: 'FEATURE',
    industry_status_item1: "By carrying out gamer's self-governance and <span>smart contract</span>, ranking list of game and comment content, and recommendation strategy, are truly transparent and impartial, eliminating the affection of capital and power.",
    industry_status_item2: "Grasp the <span>original source</span>. We are the world's first hard core technology team that can develop our own Blockchain game engine professional software. BCreator.io supports developers to start their dreams; This is a place where a huge number of developers gather.",
    industry_status_item3: 'In 5G era, <span>click and play</span>, no need to download and install; This is new form of entrance for large-scale games. “HQ HTML5”, in the era of <span>mobile internet broadband</span>, because of unlimited traffic and the major advantage of 5G, will surely become the new standard of the industry.',
    industry_status_item4: '<span>Big data base</span> of valuable reputation. The historical behaviors of developers and reviewers are all branded by smart contract into the Blockchain, which can be traced and cannot be tampered with, forming big data which various decision-making is based on.',
    
    industry_status_feature1: 'Virtual distributed structure',
    industry_status_feature2: 'High efficiency and low cost operation mode',
    industry_status_feature3: 'Decentralized structure',
    industry_status_feature4: 'Multi-node consensus mechanism',
    industry_status_feature5: 'Distributed ledger',

    //#service
    service_title1: 'INDUSTRY',//Industry background and problems
    service_title2: '&nbspBACKGROUND AND PROBLEMS',
    service_title_item1: 'The window period of seize the renaissance strategic high ground',
    service_text_item1: 'Chinese game is no longer an incremental market, but the era of retaining the user, the key is quality and playability, game <span>is returning to the beginning of heart</span>. The <span>genuine paid</span> consciousness of Chinese players is full of <span>rejuvenation</span>. The sun of game renaissance golden time is rising up. this is a window period to attract developer and fans, and snatch strategic high ground.',
    service_title_item2: 'The mode of game crowdfunding is ripe',
    service_text_item2: 'As of September 2017, the number of global game crowdfunding has reached 40000, raising a total of 900 million dollars, and 15 million users participate it. However, the <span>potential energy contradiction</span> of Chinese game industry is prominent: On the one hand, the <span>user number of pay</span> for outstanding game works have been very large. But on the other hand, potential team is <span>difficult to finance</span>, this potential energy contradiction urgently needs to be broken to <span>flood discharge</span> by a mode.',
    service_title_item3: 'Blockchain + Game Emerge',
    service_text_item3: 'There has been a lack of real projects in the area of blockchain, a lot of <span>empty words</span>. Excellent technology took the lead in the field of game once again. It focuses more players on the blockchain, and the investors of coin circle more accept the game projects. Global financing through digital currency is twice as the <span>traditional VC</span>, it is a strong <span>N<sub>2</sub>O accelerator</span> for crowdfunding.',
    
    //#portfolio
    portfolio_title1: 'SOLUTION',//Solution and implementation
    portfolio_title2: '&nbspAND IMPLEMENTING',
    portfolio_title_item1: 'Overall Solution',
    portfolio_title_item2: 'Make Game',
    portfolio_title_item3: 'Play Game',
    portfolio_title_item4: 'Communication',
    portfolio_title_item5: 'The Application of Blockchain',

    Grid_title_item1: 'Game Crowdfunding Community',
    Grid_text_item1: 'Community members invest in outstanding creative projects, obtain the return such as the work and the pre purchase right of related resources, even appreciation and so on, the success of crowdfunding is to reach or exceed the target amount, otherwise it will be returned to the sponsor.',
    Grid_title_item2: 'Tailored Create Tool',
    Grid_text_item2: 'Provides the only <span>international</span> high quality game engine in <span>Chinese</span> BCreator.io(The English version and japanese version will also be published.), it include graphical NLP of <span>programming-free</span> interactive logic module Director, greatly reduce the technical threshold, supply to developers to choose to create game.',
    Grid_title_item3: 'High Quality Game Distribution Platform',
    Grid_text_item3: 'Community attract excellent works and developers, growing popularity, and attract players through events, live broadcast, advertisement. After gathering a large number of players, they can further attract more works and excellent developers, form a <span>benign cycle</span>.',
    Grid_title_item4: 'Click It to Play HTML5 2.0',
    Grid_text_item4: 'realized convert the existing large and high quality <span>native</span> games to be <span>Click it toplay without download and install</span> H5(Instant APP) mode. Welcome unlimited traffic, Gigabit 4G、5G <span>mobile broadband</span> Internet new era, establishment of an epoch-making new form of game entry mode.',
    Grid_title_item5: 'High Level Comment',
    Grid_text_item5: 'Implementing <span>competition</span> and <span>incentive</span> mechanisms, and promoting content selecting review groups.',
    Grid_title_item6: 'Face the Opinion of Fans',
    Grid_text_item6: 'The player and the developer <span>communicate directly</span>, grind the work.',
    Grid_title_item7: 'IM System',
    Grid_text_item7: 'IM system, providing <span>instant messaging</span> services for users',
    Grid_title_item8: 'Live Broadcast System',
    Grid_text_item8: 'Effectively improve community <span>activity</span> and improve the <span>revenue</span> of game products.',
    Grid_title_item9: 'Interactive Community',
    Grid_text_item9: '<span>A fair and transparent</span> incentive mechanism based on blockchain. Players, developers, investors, critics and promoters interact within the community, their interaction is performed <span>by smart contracts</span>, and it will branded in the blockchain. Every member of the community will takes the initiative as a host to promote and build their own community.',
    Grid_title_item10: 'The SDK of Blockchain Access',
    Grid_text_item10: 'SDK based on blockchain, realize decentralization game account and the <span>right</span> of digital assets, and the <span>perforation</span> of cross-game <span>trade</span>, achieve one-click login of game, token settlement of platform, access of digital assets right verification and the perforation of trade.',
    Grid_title_item11: 'Conscientious Competition Incentive Mechanism',
    Grid_text_item11: 'The two quality competitive incentive mechanisms supported by blockchain. The excellence of the works and work comments UGC is entirely <span>determined by the player</span>, ensure the high quality of the community. The blockchain will guarantee <span>no one</span> including the founding team of the blockchain can <span>control and tamper with</span> the two competitive incentive mechanisms.',
    Grid_title_item12: 'Reputation Database Treasure',
    Grid_text_item12: 'Control click farming behavior through coindays consumption, the history score, behavior, develop historical track of works, and the commenting behavior of critics will branded in the blockchain by smart contract, become a reputation database that <span>traceability but can not be tampered with</span>. ',

    //#competitive
    competitive_title1: 'COMPETITIVE',//Competitive advantage
    competitive_title2: '&nbspADVANTAGE',
    competitive_title_item1: 'Sign with Billion Revenue Product',
    competitive_text_item1: 'Sign with product that has <span>billion</span> revenue, on the beginning of the community came online, it has <span>more than ten</span> commercial profits mature masterpiece.',
    competitive_title_item2: 'Deep Industry Resources',
    competitive_text_item2: '<span>More than ten years</span> of game development and operation experience, has deep game industry resource, experience and internet contacts.',
    competitive_title_item3: 'Click it to play HTML5 2.0',
    competitive_text_item3: '<span>Convert existing</span> high quality <span>native</span> game to achieve "Click it to play without download and install" mode. New entrance standard of <span>mobile broadband</span> internet era!',
    competitive_title_item4: 'Mature Game Production Tool Software Engine',//'Mature game production tool software engine'
    competitive_text_item4: 'Mature and available game make tool Bcreator.io',//
    competitive_title_item5: 'Mature Live Broadcast Software System',
    competitive_text_item5: 'Live games in the community, greatly improving the community activity and adhesion.',

    competitive_title_item6: 'Smart Contracts Graphical Programming-free Programming Tool',//??
    competitive_text_item6: 'programming-free smart contracts programming tool AISC, return the convenience of tradition that write contract by words.',

    //#price
    price_title1: 'PRODUCT',//Product display
    price_title2: '&nbspDISPLAY',

    price_item1: 'The monthly revenue of 《三国志2017》 reached 100 million yuan',
    price_item2: 'The monthly revenue of 《全民乐舞》 reached ten million yuan',
    price_item3: '《真三国战纪》 tribute to the classic works',
    price_item4: 'Cash flow game 《来啊捕鱼》',
    price_item5: 'Saudi Arabia Edu-game 《عالم أريب》',
    price_item6: '《初代吸血鬼》‘s  monthly revenue reached 50000 dollars of each server',
    price_item7: '《Beauty and the beast》',
    price_item8: 'Pixel IO game 《我的坦克》',
    price_item9: 'H5 《クリプトアイランド》',
    price_item10: '《梦幻3D》',
    price_item11: 'H5 《直播秀场百人德州》',
    price_item12: '《幻想学院》 monthly revenue reached ten million yuan',

    //#team
    team_title: 'TEAM',//Team introduction
    team_title_intro: '&nbspINTRODUCTION',
    team_title1: 'The Main Team',
    team_title2: 'Consultant Team',
    team_title3: 'Cooperative Partner',

    team_name_item1: 'Ali Dagli',
    team_text_item1: 'Ph.D. in Finance, Berkeley, California, Senior investor and financial strategist in the Digital Media area. Vice President of GCA Savvian, he operate the Japanese social giant Gree, and he has use 2.1 billion acquisition Funzio, Saban Brands acquisition The Playforge and other famous case. Since 2013, he conducted in-depth studies and practices on blockchain finance.',
    team_name_item2: 'Thomas Lindgren',
    team_text_item2: 'Western University MBA. senior personage on game industry, he used to be CEO of the Swedish game company Stardoll, the productor of Fatshark AB.',
    team_name_item3: 'Oliver Wu',
    team_text_item3: 'Ph.D., University of Pennsylvania, the productor of famous classic text MUD “Three Kindgoms wizard”, MMO game "Warhammer: end times ". he used to be responsible person in Singapore Interactive Media Center, responsible for the development and operation of the virtual reality world of the Youth Olympic  Games. As a former overseas president of Zhongqingbao.',
    team_name_item4: 'Abdullah Konash',
    team_text_item4: 'Harvard University, music art theory researcher. He has 9 years experience in the game industry, and  longs to lead the development of the Saudi Arabia’s game industry. He was the producer of Hako Games, Ranam.',
    
    team_name_item0: 'Dong Hao',
    team_text_item0: 'Master of software of Shanghai Jiao tong University, engineer of Perfect World research center, the former CTO of VRSTANDARD which be called VR Huangpu Military Academy, the founder of C²engine. He has 15 years of experience in the game industry, producing a number of profitable commercial masterpiece Division. From 2014, he started to study the application of blockchain in the game industry.',
    
    team_name_item5: 'Feng Tao',
    team_text_item5: 'The chairman of New Margin. The creator of Sina and many other famous business legend, he was selected  to Forbes China 2017 best venture capital Top three with Shen Nanpeng and others. In the early period of Blockchain field he had supported INB, OK, NEO, BigONE, Beechat and other projects.',
    team_name_item6: 'Frank Liu',
    team_text_item6: 'The postdoctoral researcher of Singapore Nanyang Technological University, he has a number of patents Intellectual property and very deep mathematics foundation. He also has deep research on 3D graphics, crytography, peer-to-peer communications, blockchain consensus mechanism.',
    team_name_item7: 'Yi Lihua',
    team_text_item7: 'Founding Partner of Youling Capital and INBlockchain (Coin Capital). Had invested in quantum chain, VeChain, RadarWin, BigONE more than 30 blockchain projects, covering quantitative funds, blockchain matrix Gold, code audit, exchange and other fields.',
    team_name_item8: 'Tan Qunzhao',
    team_text_item8: 'The EMBA of East China University of Science and Technology, Peking University. The founder of Fenghou investment management company and co-founder of Shanda, he used to be the chairman and chief executive official of Shanda, made a huge contribution for the Shanda game and the Chinese game industry.',
    team_name_item9: 'Li Chong',
    team_text_item9: 'Angel Investor, the sponsor of DL Capital, Co-Founder of PPTV. Focus on the mobile Internet, blockchain and other fields, emerge Bubi blockchain, SandiJianke, Boqi, P2 joint office and a large number of outstanding project.',
    team_name_item10: 'Liu Jialing（Cancer）',
    team_text_item10: 'Evangelist and investor in early national blockchain project, founding members of Bit participants and  early participants of Ethereum Project, member of Bitshares council, member of YOYOW team、the investor of ATMatrix Smart matrix.',
    team_name_item11: 'Jin Peng',
    team_text_item11: 'Ph.D. of Fudan University, his mentor is Political Bureau of the CPC Central Committee Standing Committee Professor Wang Huning. Former Senior Vice President of Shanda Network, the partner of Shanghai Lianchuang Management company, Founder of Wuqiongchuangtou, he invested in a large number of emerging industries in games, entertainment, digital Finance and marketing.',   
    team_name_item12: 'Lee Hills',
    team_text_item12: 'The entrepreneurs and senior adviser of the computer game, he is good at emerging industry, focus on the field of blockchain and financial technology. He is the founder of SolutionsHub Limited and the co-dounder of Oliver Charles Sports Management.',
    
    team_name_item13: 'Jie Mao',
    team_text_item13: 'Original vice president and chairman of Shanghai Ganglian E-commerce Co.,Ltd, strive for the best from company foundation to company listing.Shanghai Ganglian E-commerce Co.,Ltd (share code: 300226) is a national large scale comprehensive IT service enterprise that combines steel news, E-commerce, and network technological service. It provides professional steel news interactive platform, one-stop steel e-commerce service.',
    team_name_item14: 'Xiaoqi Xin',
    team_text_item14: 'I have eleven years\' work experience in game industry. I once participated in production of many large scale network games including "Star Wars : The Old Republic". With many years\' management experience and operation experience in high load project development, I joined Game.Fund in 2017, and I am responsible for community operation and user quantity growth now.',
    team_work_item3: 'Founder CEO',
    team_work_item0: 'Co-founder  CTO',
    team_work_item13: 'Co-founder  COO',
    team_work_item6: 'System Architect',
    team_work_item14: 'Operations Director',
  
    //#community
    community_title1: 'COMMUNITY',//Community Ecology
    community_title2: '&nbspECOLOGY',
    community_img_title: 'GCC Token Distribution Plan',
    community_title_item1: 'Content & Promotion Incentive 30%',//需要修改
    community_text_item1: '20% of GCC is launched directly to the community',
    community_title_item2: 'Sold 40%',
    community_text_item2: '45% of GCC is used to community content incentive, maintaining and improving the high quality of community content. The incentive will be objectively implemented by smart contract according to the community rules',
    community_title_item3: 'Advisors 10%',
    community_text_item3: '5% of GCC is held by early angel, with their support, the community has the foundation of the present, and it will locked within one year of community operation. ',
    community_title_item4: 'Dev-Community Incentive 10%',
    community_text_item4: '15% of GCC is used to motivate GameChain ecological foundation builders and partners to tamp the ecosystem.',
    community_title_item5: 'Team 10%',
    community_text_item5: '15% of GCC is held by the main team, and it will locked within one year of community operation.',

    total_content_item1: 'GCC the token of GameChain is the community status symbol. Total amount of GCC is 5 billion,accurate to 10<sup>-8</sup>，the circulation will never increase.',

    community_video_title: 'Community Operation',
    video_tag_tip: 'Your browser does not support video tags',
    community_video_text1: 'Is not a bit brain burning? All right, Please read this passage',
    community_video_text2: 'Simply put, the role of the community value of the transfer of behavior are based on GCC. Mechanism of coin days and coin days guarantee to encourage users to keep GCC and avoid brush credit and ranking. The community charge income of game crowdfunding and game distribution at different rates. One part of the income used for community constraction and maintenance, at least 50% regularly assigned to the corresponding address according to the GCC holding ratio. With the expansion of the community by promotion, more and more users to join the community, GCC\'s value will go up.',

    //#contact
    contact_we: 'Contact Us',
    contact_broadcast_group: 'Notice Address：',
    contact_chat_group: 'Chat Address：',
    contact_mail: 'E-mail：',
    broadcast_group: 'Broadcast Group',
    chat_group: 'Chat Group',
}
